// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Download documents
 */
interface DownloadDocumentData {
  /**
   * Title field in *Download*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Download*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Download field in *Download*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: download.download
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  download: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * File type field in *Download*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: download.file_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  file_type: prismic.SelectField<"PDF" | "Word" | "Powerpoint">;
}

/**
 * Download document from Prismic
 *
 * - **API ID**: `download`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DownloadDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DownloadDocumentData>,
    "download",
    Lang
  >;

type LessonDocumentDataSlicesSlice = never;

/**
 * Content for Lesson documents
 */
interface LessonDocumentData {
  /**
   * Title field in *Lesson*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Lesson*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Cover Image field in *Lesson*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Type field in *Lesson*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"Lesson" | "Lesson Video" | "Discussion">;

  /**
   * Slice Zone field in *Lesson*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LessonDocumentDataSlicesSlice>;
}

/**
 * Lesson document from Prismic
 *
 * - **API ID**: `lesson`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LessonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LessonDocumentData>, "lesson", Lang>;

/**
 * Item in *Module → Lesson*
 */
export interface ModuleDocumentDataLessonItem {
  /**
   * Lesson field in *Module → Lesson*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: module.lesson[].lesson
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  lesson: ContentRelationshipFieldWithData<
    [{ id: "lesson"; fields: ["title"] }]
  >;
}

/**
 * Content for Module documents
 */
interface ModuleDocumentData {
  /**
   * Title field in *Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Position field in *Module*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: module.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  position: prismic.NumberField;

  /**
   * Description field in *Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Colour field in *Module*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: module.colour
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  colour: prismic.ColorField;

  /**
   * Lesson field in *Module*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: module.lesson[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  lesson: prismic.GroupField<Simplify<ModuleDocumentDataLessonItem>>;
}

/**
 * Module document from Prismic
 *
 * - **API ID**: `module`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ModuleDocumentData>, "module", Lang>;

type PageDocumentDataSlicesSlice =
  | IconTextHighlightSlice
  | MediaSlice
  | TextSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Secondary Navigation*
 */
export interface SettingsDocumentDataSecondaryNavigationItem {
  /**
   * Nav Item field in *Settings → Secondary Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.secondary_navigation[].nav_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_item: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Logo Alt field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo_alt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_alt: prismic.ImageField<never>;

  /**
   * Favicon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Share Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.share_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  share_image: prismic.ImageField<never>;

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Site Description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  site_description: prismic.RichTextField;

  /**
   * Site Keywords field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_keywords: prismic.KeyTextField;

  /**
   * Site canonical url field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_canonical_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_canonical_url: prismic.KeyTextField;

  /**
   * Copyright line field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright_line
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_line: prismic.KeyTextField; /**
   * Secondary Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.secondary_navigation[]
   * - **Tab**: Navigations
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  secondary_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataSecondaryNavigationItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | DownloadDocument
  | LessonDocument
  | ModuleDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *IconTextHighlight → Default → Primary*
 */
export interface IconTextHighlightSliceDefaultPrimary {
  /**
   * Icon field in *IconTextHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_text_highlight.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Text field in *IconTextHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_text_highlight.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for IconTextHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Uses a single icon or marker next to a text block to emphasize important information.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconTextHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconTextHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *IconTextHighlight → WithDownloads → Primary*
 */
export interface IconTextHighlightSliceWithDownloadsPrimary {
  /**
   * Icon field in *IconTextHighlight → WithDownloads → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_text_highlight.withDownloads.primary.icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Text field in *IconTextHighlight → WithDownloads → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_text_highlight.withDownloads.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * WithDownloads variation for IconTextHighlight Slice
 *
 * - **API ID**: `withDownloads`
 * - **Description**: Uses a single icon or marker next to a text block to emphasize important information.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconTextHighlightSliceWithDownloads = prismic.SharedSliceVariation<
  "withDownloads",
  Simplify<IconTextHighlightSliceWithDownloadsPrimary>,
  never
>;

/**
 * Slice variation for *IconTextHighlight*
 */
type IconTextHighlightSliceVariation =
  | IconTextHighlightSliceDefault
  | IconTextHighlightSliceWithDownloads;

/**
 * IconTextHighlight Shared Slice
 *
 * - **API ID**: `icon_text_highlight`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconTextHighlightSlice = prismic.SharedSlice<
  "icon_text_highlight",
  IconTextHighlightSliceVariation
>;

/**
 * Primary content in *Media → Default → Primary*
 */
export interface MediaSliceDefaultPrimary {
  /**
   * Image field in *Media → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Media Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Media → Video → Primary*
 */
export interface MediaSliceVideoPrimary {
  /**
   * Poster field in *Media → Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.video.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Media → Video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: media.video.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;
}

/**
 * Video variation for Media Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<MediaSliceVideoPrimary>,
  never
>;

/**
 * Primary content in *Media → Image with caption → Primary*
 */
export interface MediaSliceImageWithCaptionPrimary {
  /**
   * Image field in *Media → Image with caption → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.imageWithCaption.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image with caption variation for Media Slice
 *
 * - **API ID**: `imageWithCaption`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSliceImageWithCaption = prismic.SharedSliceVariation<
  "imageWithCaption",
  Simplify<MediaSliceImageWithCaptionPrimary>,
  never
>;

/**
 * Primary content in *Media → Hero Image → Primary*
 */
export interface MediaSliceHeroImagePrimary {
  /**
   * Image field in *Media → Hero Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.heroImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Hero Image variation for Media Slice
 *
 * - **API ID**: `heroImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSliceHeroImage = prismic.SharedSliceVariation<
  "heroImage",
  Simplify<MediaSliceHeroImagePrimary>,
  never
>;

/**
 * Primary content in *Media → Hero Video → Primary*
 */
export interface MediaSliceHeroVideoPrimary {
  /**
   * Image field in *Media → Hero Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.heroVideo.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Hero Video variation for Media Slice
 *
 * - **API ID**: `heroVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSliceHeroVideo = prismic.SharedSliceVariation<
  "heroVideo",
  Simplify<MediaSliceHeroVideoPrimary>,
  never
>;

/**
 * Slice variation for *Media*
 */
type MediaSliceVariation =
  | MediaSliceDefault
  | MediaSliceVideo
  | MediaSliceImageWithCaption
  | MediaSliceHeroImage
  | MediaSliceHeroVideo;

/**
 * Media Shared Slice
 *
 * - **API ID**: `media`
 * - **Description**: Media
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSlice = prismic.SharedSlice<"media", MediaSliceVariation>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Body field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Heading → Primary*
 */
export interface TextSliceHeadingPrimary {
  /**
   * Title field in *Text → Heading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.heading.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Heading variation for Text Slice
 *
 * - **API ID**: `heading`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceHeading = prismic.SharedSliceVariation<
  "heading",
  Simplify<TextSliceHeadingPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceHeading;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DownloadDocument,
      DownloadDocumentData,
      LessonDocument,
      LessonDocumentData,
      LessonDocumentDataSlicesSlice,
      ModuleDocument,
      ModuleDocumentData,
      ModuleDocumentDataLessonItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSecondaryNavigationItem,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      IconTextHighlightSlice,
      IconTextHighlightSliceDefaultPrimary,
      IconTextHighlightSliceWithDownloadsPrimary,
      IconTextHighlightSliceVariation,
      IconTextHighlightSliceDefault,
      IconTextHighlightSliceWithDownloads,
      MediaSlice,
      MediaSliceDefaultPrimary,
      MediaSliceVideoPrimary,
      MediaSliceImageWithCaptionPrimary,
      MediaSliceHeroImagePrimary,
      MediaSliceHeroVideoPrimary,
      MediaSliceVariation,
      MediaSliceDefault,
      MediaSliceVideo,
      MediaSliceImageWithCaption,
      MediaSliceHeroImage,
      MediaSliceHeroVideo,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceHeadingPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceHeading,
    };
  }
}
