// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  media: dynamic(() => import("./Media")),
  text: dynamic(() => import("./Text")),
};
