// Code generated by Prismic. DO NOT EDIT.

import Hero from "./Hero";
import IconTextHighlight from "./IconTextHighlight";
import Media from "./Media";
import Text from "./Text";

export const components = {
	hero: Hero,
	icon_text_highlight: IconTextHighlight,
	media: Media,
	text: Text
};