// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  hero: dynamic(() => import('./Hero')),
  icon_text_highlight: dynamic(() => import('./IconTextHighlight')),
  media: dynamic(() => import('./Media')),
  text: dynamic(() => import('./Text')),
};
